version: '3'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: houssem
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  achat-app:
    depends_on:
      - mysqldb
    image: houssemkharroubi21/achatt:174
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "houssem",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update",
          "management.endpoints.web.exposure.include": "*",
          "management.endpoint.health.show-details": "always"
        }
    stdin_open: true
    tty: true

  frontend:
    image: houssemkharroubi21/front_dev:latest
    ports:
      - "4200:80"
    depends_on:
      - achat-app

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "8087:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

volumes:
  db:
