version: "3.8"

services:
   mysqldb:
     image: mysql:5.7
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD:
       MYSQL_DATABASE: achatdb
       MYSQL_ALLOW_EMPTY_PASSWORD: true
     ports:
       - 3306:3306
     volumes:
       - db:/var/lib/mysql
   app-achat:
     depends_on:
       - mysqldb
     image: zahrakr/achat-1.0:1.0
     restart: on-failure
     ports:
       - 8089:8089
     environment:
       SPRING_APPLICATION_JSON: '{
         "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
         "spring.datasource.username" : "root",
         "spring.datasource.password" : null ,
         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
         "spring.jpa.hibernate..ddl-auto" : "update"
       }'
     stdin_open: true
     tty: true

   frontend:
     image: zahrakr/front:1.0
     ports:
       - "4200:4200"
     depends_on:
       - achat-app

volumes:
  db :


