version: '3.8'

services:
  # MySQL database service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot application service
  app:
    image: medazizbay/achat:latest
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: 'true'
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: 'true'




  # Frontend application service
  achat-frontend:
    image: medazizbay/frontend:latest # Specify the image name here
    restart: unless-stopped
    ports:
      - "80:80"


volumes:
  mysql-data:
