version: '3'
services:
  achat-app:
    image: yosrabenchaaben/achat-devops:1.0
    ports:
      - "8089:8089"
    restart: on-failure
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/SpringMVC
      - SERVER_PORT=8089
      - SPRING_DATASOURCE_URL=jdbc:mysql://achat-db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD:  # Laissez vide
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network
  frontend:
    image: yosrabenchaaben/front_devops:1.0
    ports:
      - "8085:80"
    depends_on:
      - achat-app
volumes:
  mysql_data:

