version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  achat-app:
    depends_on:
      - mysqldb
    image: yosrabenchaaben/achat-devops:1.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  :"jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNoExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    stdin_open: true
    tty: true
  frontend:
    image: yosrabenchaaben/front_devops:1.0
    ports:
      - 8085:80
    depends_on:
      - achat-app
volumes:
  db: